# Generated by Django 4.1.7 on 2023-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cake_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
