# Generated by Django 4.1.7 on 2023-03-23 16:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cake_pic_alter_cake_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.CharField(blank=True, choices=[('round', 'round'), ('square', 'square'), ('heart', 'heart'), ('other', 'other')], default=builtins.round, max_length=200, null=True),
        ),
    ]
