# Generated by Django 4.1.7 on 2023-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cake_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.CharField(blank=True, choices=[('round', 'round'), ('square', 'square'), ('heart', 'heart'), ('other', 'other')], default='round', max_length=200, null=True),
        ),
    ]
