# Generated by Django 4.1.7 on 2023-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('posterpic', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
